### ISSUE TITLE
install ws-rtsp-proxy problem

### ISSUE THREAD

**Issue by bluceldg** [SpecForge/html5_rtsp_player#3]
I install  ws-rtsp-proxy with "apt install ws-rtsp-proxy",  but nothing installed like this picture
![uks t91t4ze 5te3y 0i](https://cloud.githubusercontent.com/assets/13479392/15668978/7f5cf092-2750-11e6-8c77-3ebd778f625f.png)

    I guess ws-rtsp-repo-1.2.deb is Incomplete package,Can you  send a complete package to luodanguojunli@gmail.com, thanks.

**Comment by victorgrenke** [comment]
We have fixed the package. Need to reinstall it:
apt remove ws-rtsp-proxy
wget http://repo.tom.ru/deb/debian/non-free/all/ws-rtsp-repo-1.2.deb
dpkg -i ./ws-rtsp-repo-1.2.deb
apt update
apt install ws-rtsp-proxy

because the package is depend of systemd, it supports quite last versions of debian/ubuntu

**Comment by victorgrenke** [comment]
We have fixed the package. Need to reinstall it:
apt remove ws-rtsp-proxy
wget http://repo.tom.ru/deb/debian/non-free/all/ws-rtsp-repo-1.2.deb
dpkg -i ./ws-rtsp-repo-1.2.deb
apt update
apt install ws-rtsp-proxy

because the package is depend of systemd, it supports quite last versions of debian/ubuntu

**Comment by victorgrenke** [comment]
We have fixed the package. Need to reinstall it:
apt remove ws-rtsp-proxy
wget http://repo.tom.ru/deb/debian/non-free/all/ws-rtsp-repo-1.2.deb
dpkg -i ./ws-rtsp-repo-1.2.deb
apt update
apt install ws-rtsp-proxy

because the package is depend of systemd, it supports quite last versions of debian/ubuntu

**Comment by bluceldg** [comment]
hi,
   I finished it follow above steps, nothing error report. but service ws-rtsp-proxy already can not running,
![t31clbkt 113tvz u440k9](https://cloud.githubusercontent.com/assets/13479392/15715283/739a2f30-2850-11e6-8bcd-8abdb7ced4b6.png)

   Can you help me analyze possible causes.
System version：ubuntu16-64amd

**Comment by victorgrenke** [comment]
according to documentation need to write 
> service ws_rtsp start

**Comment by videoanalytica** [comment]
I'm still having the same issue here. I downloaded rtsp-repo-1.3-all.deb and installed ws-rtsp-proxy 1.2-1. 
When trying to write service ws_rtsp start, it shows Failed to start ws_rtsp.service: Unit ws_rtsp.service not found.
I think the ws-rtsp-proxy 1.2-1 package is still not complete. Also I can not find /etc/ws_rtsp.ini on my machine.
I'm running ubuntu 16.04 64bit version.

**Comment by victorgrenke** [comment]
hello

Thank you for information I will see


21.06.2016 5:46, videoanalytica пишет:

**Comment by mempf** [comment]
I am having the same problem as videoanalytica.

`service ws_rtsp start`
`Failed to start ws_rtsp.service: Unit ws_rtsp.service not found.`

**Comment by victorgrenke** [comment]
if the service does not start - most likely something was not installed.

Could you say what's system do you use?


29.07.2016 9:45, Josh Ancill пишет:

**Comment by mempf** [comment]
Ubuntu 16.04 64bit. Installed the rtsp-repo-1.3-all.deb package followed by an "apt install ws-rtsp-proxy"

**Comment by victorgrenke** [comment]
I have put new version ws-rtsp-proxy to repo, try to install it. I hope 
this problem's fixed.


29.07.2016 14:46, Josh Ancill пишет:
